# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update archlinux
        run: pacman -Syu git --needed --noconfirm

      - name: Build arch packages
        run: |
          cd fzpac-git
          git remote set-url origin https://aur.archlinux.org/fzpac-git.git  
          git pull
          makepkg -scC
          cd man-pages-ja
          git remote set-url origin https://aur.archlinux.org/man-pages-ja.git
          git pull
          makepkg -scC
          cd paru-bin
          git remote set-url origin https://aur.archlinux.org/paru-bin.git  
          git pull
          makepkg -scC
          cd ttf-hackgen-nerd
          git remote set-url origin https://aur.archlinux.org/ttf-hackgen-nerd.git  
          git pull
          makepkg -scC



