# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    - cron: '0 10 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux
      volumes:
        - /home/runner/work/PKGBUILDs/PKGBUILDs:/tmp/pkgbuilds

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Install requirements
        run: |
          pacman -Sy base-devel --needed --noconfirm
          sed -i "s|exit \$E_ROOT|#exit \$E_ROOT|" /usr/bin/makepkg

      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Git Submodule Update                                                  
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

      - name: Build paru-bin
        run: |
          cd paru-bin
          makepkg -s --noconfirm

      - name: Build man-pages-ja
        run: |
          cd man-pages-ja
          makepkg -s --noconfirm

      - name: Build ttf-hackgen-nerd
        run: |
          cd ttf-hackgen-nerd
          makepkg -s --noconfirm

      - name: Create repo
        run: |
          mkdir repo
          ls .
          cd repo
          cp ../paru-bin/paru-bin-*-x86_64.pkg.tar.zst ../man-pages-ja/man-pages-ja-*-any.pkg.tar.zst ../ttf-hackgen-nerd/ttf-hackgen-nerd-*-any.pkg.tar.zst .
          repo-add custom.db.tar.gz *.pkg.tar.zst

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: pkgs-x86_64
          path: repo

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pkgs-x86_64

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          files: |
            *.tar.*
            custom.db
            custom.files

