# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Runs a single command using the runners shell
      - name: Install requirements
        run: |
          sudo apt-get install -y wget fakeroot
          wget "https://github.com/u0a266/archlinux-tools-deb/releases/download/2021.06.19/pacman-arch_6.0.0_amd64.deb"
          wget "https://github.com/u0a266/archlinux-tools-deb/releases/download/2021.06.19/archlinux-keyring_20210616_amd64.deb"
          wget "https://github.com/u0a266/archlinux-tools-deb/releases/download/2021.06.19/arch-install-scripts_24_amd64.deb"
          wget "https://github.com/u0a266/archlinux-tools-deb/releases/download/2021.06.19/archiso_55_amd64.deb"
          sudo apt-get -y install ./*.deb
          sudo mkdir -pv /etc/pacman.d
          sudo sh -c 'curl "https://archlinux.org/mirrorlist/?country=all&protocol=http&protocol=https&ip_version=4&use_mirror_status=on" | sed s/#S/S/g > /etc/pacman.d/mirrorlist'

      - name: Build paru-bin
        run: |
          cd paru-bin
          makepkg -d --noconfirm

      - name: Build man-pages-ja
        run: |
          cd man-pages-ja
          makepkg -d --noconfirm

      - name: Build ttf-hackgen-nerd
        run: |
          cd ttf-hackgen-nerd
          makepkg -d --noconfirm

      - name: Create repo
        run: |
          mkdir repo
          ls .
          ls paru-bin
          cd repo
          cp ../paru-bin/paru-bin-*-x86_64.pkg.tar.zst ../man-pages-ja/man-pages-ja-*-any.pkg.tar.zst ../ttf-hackgen-nerd/ttf-hackgen-nerd-*-any.pkg.tar.zst .
          repo-add custom.db.tar.zst *.pkg.tar.zst

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: pkgs-x86_64
          path: repo

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pkgs-x86_64

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          files: |
            *.tar.*
            custom.db
            custom.files

